# Generated by Django 4.2.9 on 2024-09-20 10:51

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon', models.CharField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_name', models.CharField(max_length=255)),
                ('video_id', models.CharField(max_length=500)),
                ('category', models.CharField(choices=[('Kokrakvatriceps', "Ko'krak va triceps"), ('QanotmashqlarivaBiceps', 'Qanot mashqlari va Biceps'), ('Qanotmashqlari', 'Qanot mashqlari'), ('Yelkamashqlari', 'Yelka mashqlari'), ('Oyoqmashqlari', 'Oyoq mashqlari'), ('Uysharoitidamashqlar(Erkaklaruchun)', 'Uy sharoitida mashqlar (Erkaklar uchun)'), ('Uysharoitidamashqlar(Ayollaruchun)', 'Uy sharoitida mashqlar (Ayollar uchun)'), ('Kardiovajismoniymashqlar', 'Kardio va jismoniy mashqlar'), ('Pressmashqlari', 'Press mashqlari'), ('Dietavatogriovqatlanish:ErkeklarvaAyollaruchun', "Dieta va to'g'ri ovqatlanish: Erkeklar va Ayollar uchun"), ('Sportqoshimchalari', "Sport qo'shimchalari"), ('Farmakalogiya(Ximiya)', 'Farmakalogiya (Ximiya)')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('phone_number', models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(code='invalid_number', message='Invalid phone number. Format should be +998XXXXXXXXX', regex='^\\+998\\d{9}$')], verbose_name='Telefon raqam')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'abstract': False,
                'swappable': 'AUTH_USER_MODEL',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
