# Generated by Django 4.2.9 on 2024-09-20 10:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=13, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_number', message='Invalid phone number. Format should be +998XXXXXXXXX', regex='^\\+998\\d{9}$')], verbose_name='Telefon raqam'),
        ),
    ]
