# Generated by Django 4.2.9 on 2024-09-24 14:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=13, null=True, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_number', message='Invalid phone number. Format should be +998XXXXXXXXX', regex='^\\+998\\d{9}$')], verbose_name='Telefon raqam'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_name',
            field=models.CharField(max_length=555),
        ),
    ]
