# Generated by Django 4.2.9 on 2024-10-01 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_user_status_userdevice'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdevice',
            name='device_image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
